### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by WellImDumb** [001honi/vc-cycle-gan#2]
Traceback (most recent call last):
  File "train.py", line 141, in <module>
    train(train_A_dir = train_A_dir, train_B_dir = train_B_dir, model_dir = model_dir, model_name = model_name, random_seed = random_seed, validation_A_dir = validation_A_dir, output_dir = output_dir, tensorboard_log_dir = tensorboard_log_dir)
  File "train.py", line 97, in train
    if epoch % (check_epoch//2) == 0:
ZeroDivisionError: integer division or modulo by zero

**Comment by 001honi** [comment]
I assume _check_epoch_ parameter is chosen as **1** because I said earlier; however, I missed _ZeroDivisionError_ probability in this suggestion. In Python, 
`dummy = (check_epoch=1)//2 = 0` 
`epoch % (dummy=0) => ZeroDivisionError: integer division or modulo by zero` 
Thus, I think **2** is minimum acceptable value for _check_epoch_. 

> Further suggestion, you need at least 2000 epochs of training on approximately 8 minutes of dataset for each source and target voice to obtain a fair average model. You can select _check_epoch_ as **200** and after 10 repetition of model save, you got your result.
